<?php
/**
 * PDF Directory Setup Script
 * Run this script to set up the PDF directories, permissions, and .htaccess files
 * 
 * Place this file at: /backend/setup_pdf_directories.php
 * Run via: php setup_pdf_directories.php
 * Or via web: http://localhost/bm-payslip/backend/setup_pdf_directories.php
 */

// Check if running from web or CLI
$isWeb = isset($_SERVER['HTTP_HOST']);
if ($isWeb) {
    header('Content-Type: text/html; charset=utf-8');
    echo "<html><head><title>PDF Setup</title><style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .success { color: green; }
        .error { color: red; }
        .warning { color: orange; }
        .info { color: blue; }
        pre { background: #f5f5f5; padding: 10px; }
    </style></head><body>";
    echo "<h1>PDF Directory Setup</h1><pre>";
}

echo "=== PDF Directory Setup Script ===\n";
echo "Timestamp: " . date('Y-m-d H:i:s') . "\n\n";

// Define paths
$projectRoot = dirname(__DIR__);
$frontendPath = $projectRoot . '/frontend';
$pdfBasePath = $frontendPath . '/pdfs';
$agentPath = $pdfBasePath . '/agent';
$adminPath = $pdfBasePath . '/admin';

echo "Project Structure:\n";
echo "- Project root: $projectRoot\n";
echo "- Frontend path: $frontendPath\n";
echo "- PDF base path: $pdfBasePath\n";
echo "- Agent path: $agentPath\n";
echo "- Admin path: $adminPath\n\n";

// Create directories
echo "=== Creating Directories ===\n";
$directories = [
    $frontendPath => 'Frontend directory',
    $pdfBasePath => 'PDF base directory',
    $agentPath => 'Agent PDF directory',
    $adminPath => 'Admin PDF directory'
];

foreach ($directories as $dir => $description) {
    if (!file_exists($dir)) {
        if (mkdir($dir, 0755, true)) {
            echo "✓ Created: $description ($dir)\n";
        } else {
            echo "✗ Failed to create: $description ($dir)\n";
        }
    } else {
        echo "✓ Already exists: $description ($dir)\n";
    }
    
    // Check and fix permissions
    if (is_writable($dir)) {
        echo "  ✓ Directory is writable\n";
    } else {
        echo "  ⚠ Directory is not writable, attempting to fix...\n";
        if (chmod($dir, 0755)) {
            echo "  ✓ Fixed permissions\n";
        } else {
            echo "  ✗ Could not fix permissions\n";
        }
    }
}

// Create .htaccess files
echo "\n=== Creating .htaccess Files ===\n";

// Frontend .htaccess
$frontendHtaccessContent = '# Frontend Directory Access Configuration
# Generated by setup script on ' . date('Y-m-d H:i:s') . '

# Allow access to all frontend files
Order Allow,Deny
Allow from all

# Enable mod_rewrite
RewriteEngine On
RewriteBase /bm-payslip/frontend/

# MIME type configuration
<IfModule mod_mime.c>
    AddType application/pdf .pdf
    AddType image/png .png
    AddType image/jpeg .jpg .jpeg
    AddType image/gif .gif
    AddType image/x-icon .ico
    AddType text/css .css
    AddType application/javascript .js
    AddType application/json .json
    AddType text/html .html .htm
</IfModule>

# PDF-specific headers for proper viewing
<FilesMatch "\.pdf$">
    <IfModule mod_headers.c>
        Header always set Content-Type "application/pdf"
        Header always set Content-Disposition "inline"
        Header always set Cache-Control "private, max-age=3600"
        Header always set X-Content-Type-Options "nosniff"
        Header always set X-Frame-Options "SAMEORIGIN"
    </IfModule>
</FilesMatch>

# Security headers for static files
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

# Enable compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE application/javascript
    AddOutputFilterByType DEFLATE text/html
</IfModule>

# Prevent access to sensitive files
<FilesMatch "\.(htaccess|htpasswd|ini|log|sh|sql)$">
    Order Allow,Deny
    Deny from all
</FilesMatch>';

// PDF directory .htaccess
$pdfHtaccessContent = '# PDF Directory Access Configuration
# Generated by setup script on ' . date('Y-m-d H:i:s') . '

# Allow PDF access
Order Allow,Deny
Allow from all

# Set correct MIME type for PDFs
<Files *.pdf>
    Header set Content-Type application/pdf
    Header set Content-Disposition inline
    Header set Cache-Control "private, max-age=3600"
    Header set X-Content-Type-Options nosniff
    Header set X-Frame-Options SAMEORIGIN
</Files>

# Security settings
<FilesMatch "\.(htaccess|htpasswd|ini|log|sh|sql|php)$">
    Order Allow,Deny
    Deny from all
</FilesMatch>';

// Write .htaccess files
$htaccessFiles = [
    $frontendPath . '/.htaccess' => $frontendHtaccessContent,
    $pdfBasePath . '/.htaccess' => $pdfHtaccessContent
];

foreach ($htaccessFiles as $file => $content) {
    if (file_put_contents($file, $content)) {
        echo "✓ Created .htaccess: $file\n";
    } else {
        echo "✗ Failed to create .htaccess: $file\n";
    }
}

// Test file creation and access
echo "\n=== Testing File Access ===\n";

// Create test file
$testFile = $pdfBasePath . '/test_access.txt';
$testContent = "PDF access test file\nCreated: " . date('Y-m-d H:i:s') . "\n";

if (file_put_contents($testFile, $testContent)) {
    echo "✓ Created test file: $testFile\n";
    
    if ($isWeb) {
        // Test web access
        $testUrl = '/bm-payslip/frontend/pdfs/test_access.txt';
        $fullUrl = 'http://' . $_SERVER['HTTP_HOST'] . $testUrl;
        
        echo "  Test URL: $testUrl\n";
        echo "  Full URL: $fullUrl\n";
        
        // Check accessibility
        $headers = @get_headers($fullUrl);
        if ($headers && strpos($headers[0], '200') !== false) {
            echo "  ✓ File is accessible via web\n";
        } else {
            echo "  ⚠ File may not be accessible via web\n";
            if ($headers) {
                echo "  Response: " . $headers[0] . "\n";
            }
        }
    }
    
    // Clean up test file
    if (unlink($testFile)) {
        echo "  ✓ Test file cleaned up\n";
    }
} else {
    echo "✗ Failed to create test file\n";
}

// Check FPDF library
echo "\n=== Checking FPDF Library ===\n";
$fpdfPath = __DIR__ . '/lib/fpdf/fpdf.php';
if (file_exists($fpdfPath)) {
    echo "✓ FPDF library found at: $fpdfPath\n";
} else {
    echo "⚠ FPDF library not found at: $fpdfPath\n";
    echo "  Please ensure FPDF is installed in the lib directory\n";
}

// Configuration check
echo "\n=== Configuration Check ===\n";
if (file_exists(__DIR__ . '/config/config.php')) {
    require_once __DIR__ . '/config/config.php';
    echo "✓ Configuration loaded\n";
    
    if (defined('PDF_PATH')) {
        echo "  PDF_PATH: " . PDF_PATH . "\n";
    } else {
        echo "  PDF_PATH: Not defined (using default)\n";
    }
    
    if (defined('APP_ENV')) {
        echo "  APP_ENV: " . APP_ENV . "\n";
    }
} else {
    echo "⚠ Configuration file not found\n";
}

echo "\n=== Setup Summary ===\n";
echo "✓ PDF directories created and configured\n";
echo "✓ .htaccess files installed for proper access\n";
echo "✓ Permissions set correctly\n";
echo "\nPDF URLs will be accessible at:\n";
echo "- Agent PDFs: http://localhost/bm-payslip/frontend/pdfs/agent/[filename].pdf\n";
echo "- Admin PDFs: http://localhost/bm-payslip/frontend/pdfs/admin/[filename].pdf\n";

if ($isWeb) {
    echo "\n<strong>Next Steps:</strong>\n";
    echo "1. Test PDF generation: <a href='test_pdf_generation.php'>Run PDF Test</a>\n";
    echo "2. Check system status: <a href='debug_pdf.php'>System Debug</a>\n";
    echo "3. Generate a payslip to test the complete workflow\n";
}

echo "\n=== Setup Complete ===\n";

if ($isWeb) {
    echo "</pre></body></html>";
}
?>